import pygame
from settings import *

hangmanmenu = pygame.image.load(standardPathImages+"\hangman\hangman1.jpg")
hangmanstart = pygame.image.load(standardPathImages+"\hangman\hangman2.jpg")
hangmanhead = pygame.image.load(standardPathImages+"\hangman\hangmanhead.jpg")
hangmanbody = pygame.image.load(standardPathImages+"\hangman\hangmanbody.jpg")
hangmanleg = pygame.image.load(standardPathImages+"\hangman\hangmanleg.jpg")
hangmanlegtwo = pygame.image.load(standardPathImages+"\hangman\hangmanlegtwo.jpg")
hangmanarm = pygame.image.load(standardPathImages+"\hangman\hangmanarm.jpg")
hangmanarmtwo = pygame.image.load(standardPathImages+"\hangman\hangmanarmtwo.jpg")
hangmaneye = pygame.image.load(standardPathImages+"\hangman\hangmaneye.jpg")
hangmaneyetwo = pygame.image.load(standardPathImages+"\hangman\hangmaneyetwo.jpg")
hangmanmouth = pygame.image.load(standardPathImages+"\hangman\hangmanmouth.jpg")
hangmanstartmenu = pygame.image.load(standardPathImages+"\hangman\hangmanstartbutton.jpg")
dash = pygame.image.load(standardPathImages+"\hangman\dash.png")
hangmanAni = [hangmanstart, hangmanhead, hangmanbody, hangmanleg, hangmanlegtwo, hangmanarm, hangmanarmtwo, hangmaneye, hangmaneyetwo, hangmanmouth]
aImage = pygame.image.load(standardPathImages+"\hangman\letters\lettera.png")
bImage = pygame.image.load(standardPathImages+"\hangman\letters\letterb.png")
cImage = pygame.image.load(standardPathImages+"\hangman\letters\letterc.png")
dImage = pygame.image.load(standardPathImages+"\hangman\letters\letterd.png")
eImage = pygame.image.load(standardPathImages+"\hangman\letters\lettere.png")
fImage = pygame.image.load(standardPathImages+"\hangman\letters\letterf.png")
gImage = pygame.image.load(standardPathImages+"\hangman\letters\letterg.png")
hImage = pygame.image.load(standardPathImages+"\hangman\letters\letterh.png")
iImage = pygame.image.load(standardPathImages+"\hangman\letters\letteri.png")
jImage = pygame.image.load(standardPathImages+"\hangman\letters\letterj.png")
kImage = pygame.image.load(standardPathImages+"\hangman\letters\letterk.png")
lImage = pygame.image.load(standardPathImages+"\hangman\letters\letterl.png")
mImage = pygame.image.load(standardPathImages+"\hangman\letters\letterm.png")
nImage = pygame.image.load(standardPathImages+"\hangman\letters\lettern.png")
oImage = pygame.image.load(standardPathImages+"\hangman\letters\lettero.png")
pImage = pygame.image.load(standardPathImages+"\hangman\letters\letterp.png")
qImage = pygame.image.load(standardPathImages+"\hangman\letters\letterq.png")
rImage = pygame.image.load(standardPathImages+"\hangman\letters\letterr.png")
sImage = pygame.image.load(standardPathImages+"\hangman\letters\letters.png")
tImage = pygame.image.load(standardPathImages+"\hangman\letters\lettert.png")
uImage = pygame.image.load(standardPathImages+"\hangman\letters\letteru.png")
wImage = pygame.image.load(standardPathImages+"\hangman\letters\letterw.png")
vImage = pygame.image.load(standardPathImages+"\hangman\letters\letterv.png")
xImage = pygame.image.load(standardPathImages+"\hangman\letters\letterx.png")
yImage = pygame.image.load(standardPathImages+"\hangman\letters\lettery.png")
zImage = pygame.image.load(standardPathImages+"\hangman\letters\letterz.png")

